//AUTHENTICATION
export const LOGIN = 'LOGIN';

//LOADER
export const SET_LOADER = 'SET_LOADER';

////HOME
export const SET_HOME_LOADING = 'SET_HOME_LOADING';
export const GET_HOME_ACTIVITIES = 'GET_HOME_ACTIVITIES';
export const GET_HOME_LATEST_NEWS = 'GET_HOME_LATEST_NEWS';
export const GET_HOME_NEWS = 'GET_HOME_NEWS';
export const GET_HOME_OPPOTUNITY = 'GET_HOME_OPPOTUNITY';
export const GET_HOME_PBV_GROUP_PROGILE = 'GET_HOME_PBV_GROUP_PROGILE';

//GROUP
export const SET_GROUP_LOADING = 'SET_HOME_LOADING';
export const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
export const GET_MY_GROUPS = 'GET_MY_GROUPS';

///GROUP DETAILS
export const SET_GROUP_DETAILS_LOADING = 'SET_HOME_LOADING';
export const GET_GROUP_OVERVIEW = 'GET_GROUP_OVERVIEW';
export const GET_GROUP_ACTIVITIES = 'GET_GROUP_ACTIVITIES';
export const GET_GROUP_NEWS = 'GET_GROUP_NEWS';
export const GET_GROUP_LATEST_NEWS = 'GET_GROUP_LATEST_NEWS';
export const GET_GROUP_OPPORTUNITY = 'GET_GROUP_OPPORTUNITY';
export const GET_GROUP_DETAILS = 'GET_GROUP_DETAILS';
export const GET_GROUP_MEMBERS = 'GET_GROUP_MEMBERS';

//MEMBERS
export const SET_MEMBER_LOADING = 'SET_HOME_LOADING';
export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';

//USER
export const SET_USER_LOADING = 'SET_USER_LOADING';
export const GET_USER_OPPORTUNITY = 'GET_USER_OPPORTUNITY';
export const GET_USER_NEWS = 'GET_USER_NEWS';
export const GET_USER_LATEST_NEWS = 'GET_USER_LATEST_NEWS';
export const GET_USER_OVERVIEW = 'GET_USER_OVERVIEW';
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_SETTINGS = 'GET_USER_SETTINGS';
export const GET_USER_ACTIVITIES = 'GET_USER_ACTIVITIES';
export const GET_USER_NOTIFICATION_READ = 'GET_USER_NOTIFICATION_READ';
export const GET_USER_NOTIFICATION_UNREAD = 'GET_USER_NOTIFICATION_UNREAD';
export const GET_USER_EMAIL_NOTICE_CONFIG = 'GET_USER_EMAIL_NOTICE_CONFIG';

//INFO
export const SET_INFO_LOADING = 'SET_INFO_LOADING';
export const GET_FAQ = 'GET_FAQ';
export const GET_AREA_OF_PRACTICE_LIST = 'GET_AREA_OF_PRACTICE_LIST';
///////////////////////////////////////////
export const GET_LAWYER_ROLE_LIST = 'GET_LAWYER_ROLE_LIST';
export const GET_LAWYER_LIST = 'GET_LAWYER_LIST';
// export const GET_SERVICE_LINE_LIST = 'GET_SERVICE_LINE_LIST';
// export const GET_INDUSTRY_SEGMENT_LIST = 'GET_INDUSTRY_SEGMENT_LIST';
export const GET_CLIENT_DIMENSION_LIST = 'GET_CLIENT_DIMENSION_LIST';
export const GET_DEAL_CASE_DIMENSION_LIST = 'GET_DEAL_CASE_DIMENSION_LIST';
////////////////////////////////////////////
export const GET_JURISDICTION_LIST = 'GET_JURISDICTION_LIST';
export const GET_TOWN_LIST = 'GET_TOWN_LIST';
export const GET_INDUSTRY_LIST = 'GET_INDUSTRY_LIST';
export const GET_TERM_CONDITION = 'GET_TERM_CONDITION';
export const GET_PRIVACY_POLICY = 'GET_PRIVACY_POLICY';
export const GET_USER_AGREEMENT = 'GET_USER_AGREEMENT';
// export const GET_FAQ = 'SET_LOADER';
// export const GET_FAQ = 'SET_LOADER';
