//AUTHENTICATION
export const LOGIN = 'LOGIN';

//LOADER
export const SET_LOADER = 'SET_LOADER';

////HOME
export const SET_HOME_LOADING = 'SET_HOME_LOADING';
export const GET_HOME_ACTIVITIES = 'GET_HOME_ACTIVITIES';
export const GET_HOME_LATEST_NEWS = 'GET_HOME_LATEST_NEWS';
export const GET_HOME_NEWS = 'GET_HOME_NEWS';
export const GET_HOME_OPPOTUNITY = 'GET_HOME_OPPOTUNITY';
export const GET_HOME_PBV_GROUP_PROGILE = 'GET_HOME_PBV_GROUP_PROGILE';

//GROUP
export const SET_GROUP_LOADING = 'SET_HOME_LOADING';
export const GET_ALL_GROUPS = 'GET_ALL_GROUPS';
export const GET_MY_GROUPS = 'GET_MY_GROUPS';

///GROUP DETAILS
export const SET_GROUP_DETAILS_LOADING = 'SET_HOME_LOADING';
export const GET_GROUP_OVERVIEW = 'GET_GROUP_OVERVIEW';
export const GET_GROUP_ACTIVITIES = 'GET_GROUP_ACTIVITIES';
export const GET_GROUP_LATEST_NEWS = 'GET_GROUP_LATEST_NEWS';
export const GET_GROUP_OPPORTUNITY = 'GET_GROUP_OPPORTUNITY';
export const GET_GROUP_DETAILS = 'GET_GROUP_DETAILS';
export const GET_GROUP_MEMBERS = 'GET_GROUP_MEMBERS';

//MEMBERS
export const SET_MEMBER_LOADING = 'SET_HOME_LOADING';
export const GET_ALL_MEMBERS = 'GET_ALL_MEMBERS';

//USER
export const SET_USER_LOADING = 'SET_HOME_LOADING';
export const GET_USER_OPPORTUNITY = 'SET_LOADER';
export const GET_USER_LATEST_NEWS = 'SET_LOADER';
export const GET_USER_OVERVIEW = 'SET_LOADER';
export const GET_USER_PROFILE = 'SET_LOADER';
export const GET_USER_ACTIVITIES = 'SET_LOADER';
export const GET_USER_NOTIFICATION_READ = 'SET_LOADER';
export const GET_USER_NOTIFICATION_UNREAD = 'SET_LOADER';
export const GET_USER_EMAIL_NOTICE_CONFIG = 'SET_LOADER';
